blog/app.py
from flask import Flask

from blog.article.views import article
from blog.user.views import user


def create_app() -> Flask:
    app = Flask(__name__)
    register_blueprints(app)
    return app.run()


def register_blueprints(app: Flask):
    app.register_blueprint(user)
    app.register_blueprint(article)

blog/article/views.py
from flask import Blueprint, render_template
from werkzeug.exceptions import NotFound

article = Blueprint('article', __name__, url_prefix='/articles', static_folder='../static')

ARTICLES = {
    1: {
        'title': 'Статья 1',
        'text': 'Текст статьи 1',
        'author': {
            'name': 'Mark',
            'id': 1
        }
    },
    2: {
        'title': 'Статья 2',
        'text': 'Текст статьи 2',
        'author': {
            'name': 'Eugene',
            'id': 2
        }
    },
    3: {
        'title': 'Статья 3',
        'text': 'Текст статьи 3',
        'author': {
            'name': 'Karl',
            'id': 3
        }
    }
}


@article.route('/')
def article_list():
    return render_template('articles/list.html', articles=ARTICLES)


@article.route('/<int:pk>')
def content_article(pk: int):
    try:
        text_article = ARTICLES[pk]['text']
    except KeyError:
        raise NotFound(f'Article id = {pk} not found')
    return render_template('articles/content_article.html', text_content_article=[text_article, pk],
                           articles=ARTICLES[pk])

blog/user/views.py
from flask import Blueprint, render_template, redirect
from werkzeug.exceptions import NotFound

user = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


USERS = {
    1: 'Mark',
    2: 'Eugene',
    3: 'Karl'
}


@user.route('/')
def user_list():
    return render_template(
        'users/list.html',
        users=USERS,
    )


@user.route('/<int:pk>')
def get_user(pk: int):
    try:
        user_name = USERS[pk]
    except KeyError:
        raise NotFound(f'User id = {pk} not found')
        # return redirect('/users/') //перенаправляет на страницу users
    return render_template(
        'users/detail.html',
        user_name=user_name,
    )

blog/templates/articles/content_article.html
{% extends 'base.html' %}

{% block title %} Articles content {% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1> Статья {{ text_content_article[1] }}:</h1>
            <h3>{{ text_content_article[0] }}</h3>
            <h5>Автор: {{ articles['author']['name'] }} c id = {{ articles['author']['id'] }}</h5>
        </div>
    </div>
{% endblock %}

blog/templates/articles/list.html
{% extends 'base.html' %}

{% block title %} Articles list {% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>Articles:</h1>
            {% for id_article in articles %}
                <ul>
                    <li><a href="{{ url_for('article.content_article', pk=id_article) }}">{{ articles[id_article]['title'] }}</a></li>
                </ul>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block css %}
        <!-- Bootstrap CSS -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}
    <title>
        {% block title %} {% endblock %}
    </title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    {% block body %} {% endblock %}
</div>

{% block js %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
{% endblock %}
</body>
</html>


{##}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>#}
{#        {% block title %} {% endblock %}#}
{#    </title>#}
{#    {% block css %}{% endblock %}#}
{#</head>#}
{#<body>#}
{#{% block body %} {% endblock %}#}
{#{% block js %}{% endblock %}#}
{#</body>#}
{#</html>#}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('user.user_list')}}">Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('article.article_list')}}">Articles</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

blog/templates/users/detail.html
{% extends 'base.html' %}

{% block title %} Users detail {% endblock %}

{% block body %}
    <h1>{{ user_name }}</h1>
{% endblock %}

blog/templates/users/list.html
{% extends 'base.html' %}

{% block title %} Users list {% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
            <h1>Users:</h1>
            {% for user_id in users %}
                <ul>
                    <li><a href="{{ url_for('user.get_user', pk=user_id) }}">{{ users[user_id] }}</a></li>
                </ul>
            {% endfor %}
        </div>
    </div>
{% endblock %}